version: '3'
networks:
  sendanywhereNet:
    driver: bridge
services:
  nginx:
    image: nginx:1.23.1
    restart: always
    depends_on:
      - loki
      - grafana
    networks:
      - sendanywhereNet
    container_name: sendanywhere_nginx_container
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./test-coverage/integration/:/integration/:ro
      - ./test-coverage/unit/:/unit/:ro
    ports:
      - 80:80
  loki:
    image: grafana/loki:2.6.0
    container_name: sendanywhere_loki_container
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    networks:
      - sendanywhereNet
    restart: always
    volumes:
      - ./grafana/loki-local-config.yml:/etc/loki/local-config.yml
    depends_on:
      - grafana
  grafana:
    image: grafana/grafana:9.1.2-ubuntu
    container_name: sendanywhere_grafana_container
    networks:
      - sendanywhereNet
    ports:
      - "3020:3000"
    restart: always
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/loki-dashboard_rev1.json:/var/lib/grafana/dashboards/loki-dashboard_rev1.json
    #environment:
    #  - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/loki-dashboard_rev1.json
    #  - GF_SECURITY_ADMIN_USER=admin
    #  - GF_SECURITY_ADMIN_PASSWORD=admin
    env_file: 
      - ./.env